### ISSUE TITLE
Typo of millisBehindLatest

### ISSUE THREAD

**Issue by ryanyuan** [awsdocs/amazon-kinesis-data-analytics-developer-guide#12]
On [monitoring](https://docs.aws.amazon.com/kinesisanalytics/latest/java/monitoring.html) and [monitoring metrics alarms](https://docs.aws.amazon.com/kinesisanalytics/latest/java/monitoring-metrics-alarms.html), we have `millisBehindLatest` as typo `millsBehindLatest`.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
