### ISSUE TITLE
Incorrect wording

### ISSUE THREAD

**Issue by Humanavatar** [awsdocs/amazon-kinesis-data-analytics-developer-guide#5]
In the file "console-summary-sql-editor.md" the sentence "Amazon Kinesis Data Analytics provides this column only in the in-application input stream that is mapped to the streaming source.", the "in" in "only in the" is not the correct word.  It is not obvious if the author intended "in" to actually be "when" or followed by "the event".  Either way, the current wording is incorrect.

**Comment by Humanavatar** [comment]
The file is: console-summary-sql-editor.md

**Comment by fletpatr** [comment]
I think this is correct- AKDA only provides the approximate_arrival_time column in the in-application input stream. The values in the column are generated when the record is ingested into the AKDA service. For more information, see "Ingest Time" here: https://docs.aws.amazon.com/kinesisanalytics/latest/dev/timestamps-rowtime-concepts.html

**Comment by Humanavatar** [comment]
I think your explanation clarifies what is being communicated.  When I read through the documentation, this was not clear and grammatically odd.

I guess this can be closed, though it would be nice to have this sentence unpacked a bit as not everyone is reading this documentation with the AKDA knowledge needed to understand the sentence in its current structure.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
