### ISSUE TITLE
Malformed Table

### ISSUE THREAD

**Issue by jsbonso** [awsdocs/amazon-kinesis-data-analytics-developer-guide#8]
In this repo, the tables are correctly formatted. There is a certain row which contains the content below:

**"records [See the AWS documentation website for more details]"** 
Source:

https://github.com/awsdocs/amazon-kinesis-data-analytics-developer-guide/blob/master/doc_source/how-it-works-output-lambda.md

However, in the actual AWS documentation, the table is malformed:
https://docs.aws.amazon.com/kinesisanalytics/latest/dev/how-it-works-output-lambda.html

**Comment by fletpatr** [comment]
Thanks for the note! The table is actually correctly formed in the docs- the nesting of the tables shows the nesting of the data within the input data object: the "Records" field contains a nested structure that contains the record data. Similarly, the response model is a nested structure inside a "Records" field.
